
server.document-root = "/var/www/localhost/htdocs"
server.port = 8080

server.modules += ( "mod_fastcgi" )

fastcgi.server = (
    "/" => ((
        "socket" => "/tmp/compuguessr.sock",
        "check-local" => "disable"
    ))
)

