server.document-root = var.CWD + "/public"
server.port = 8080

server.modules += ( "mod_alias", "mod_fastcgi", "mod_dirlisting" )

index-file.names = ( "index.html" )

alias.url = (
    "/challenges/" => var.CWD + "/challenges/"
)

fastcgi.server = (
    "/api/" => ((
        "socket" => "/tmp/compuguessr.sock",
        "check-local" => "disable"
    ))
)

mimetype.assign = (
    ".html" => "text/html",
    ".css"  => "text/css",
    ".js"   => "application/javascript",
    ".json" => "application/json",
    ".png"  => "image/png",
    ".jpg"  => "image/jpeg"
)
