#!/usr/bin/env python3

import os
import json
import glob

CHALLENGES_DIR = "challenges"
FRONTEND_OUT = "public/challenges/challenges.json"
OUT_C = "src/data/cg_challengedb_data.c"

def escape_c_string(s):
    """Escapes quotes and newlines for C string literals."""
    if not s:
        return ""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')

def main():
    frontend_data = {"version": "1.1", "challenges": []}
    challenges = []

    search_path = os.path.join(CHALLENGES_DIR, "**", "*.json")
    files = glob.glob(search_path, recursive=True)

    for filepath in files:
        with open(filepath, 'r', encoding='utf-8') as f:
            master = json.load(f)

        # -- Build Frontend Data (Strip Secrets) --
        public_chal = {k: v for k, v in master.items() if k != "questions"}
        public_chal["questions"] = []

        for q in master.get("questions", []):
            # Keep 'points' so the UI can display them, but strip backend data
            public_q = {k: v for k, v in q.items() if k not in ("answer")}

            # Strip explanation from the individual responses
            if "responses" in public_q:
                clean_responses = []
                for r in public_q["responses"]:
                    clean_r = {k: v for k, v in r.items() if k != "explanation"}
                    clean_responses.append(clean_r)
                public_q["responses"] = clean_responses

            public_chal["questions"].append(public_q)

        frontend_data["challenges"].append(public_chal)
        challenges.append(master)

    # 2. Write the Public JSON
    os.makedirs(os.path.dirname(FRONTEND_OUT), exist_ok=True)
    with open(FRONTEND_OUT, 'w', encoding='utf-8') as f:
        json.dump(frontend_data, f, indent=2)
    print(f"[*] Wrote Frontend JSON: {FRONTEND_OUT}")

    # 3. Sort backend challenges alphabetically by ID for Binary Search
    challenges.sort(key=lambda x: x["id"])

    # 4. Generate C Source Code
    c_source = [
        "/* AUTOGENERATED FILE - DO NOT EDIT */",
        "#include <stdint.h>",
        '#include "data/cg_challengedb_data.h"',
        ""
    ]

    for chal in challenges:
        chal_id = chal["id"]
        questions = chal.get("questions", [])

        if not questions:
            continue

        c_source.append(f"static const struct cg_question q_{chal_id}[] = {{")
        total_points = 0

        for q in questions:
            ans = q["answer"]
            q_id = q["id"]
            pts = q.get("points", 0)
            total_points += pts

            # Determine Answer Type & Value
            if ans["type"] == "text":
                val = f'.answer.text_answer = "{escape_c_string(ans["value"])}"'
                enum_type = "CG_ANS_TEXT"
            elif ans["type"] == "bitmask":
                val = f'.answer.numeric_answer = {ans["value"]}'
                enum_type = "CG_ANS_BITMASK"
            elif ans["type"] == "single":
                val = f'.answer.numeric_answer = {ans["value"]}'
                enum_type = "CG_ANS_SINGLE"
            else:
                raise ValueError(f"Unknown answer type in {chal_id}")

            # Compile the Explanation String
            expl_str = ""
            if "explanation" in ans:
                expl_str = ans["explanation"]
            else:
                # If no global explanation, compile per-option explanations
                expl_parts = []
                for r in q.get("responses", []):
                    if "explanation" in r:
                        expl_parts.append(f"[{r['text']}]: {r['explanation']}")
                expl_str = "\\n".join(expl_parts)

            c_source.append(f'    {{ .id = {q_id}, .points = {pts}, .type = {enum_type}, '
                            f'{val}, .explanation = "{escape_c_string(expl_str)}" }},')

        c_source.append("};")

        # Cache the calculated total_points back into the master object
        chal["_calculated_total_points"] = total_points
        c_source.append("")

    # Generate the main Database array
    c_source.append("const struct cg_challengedb g_challengedb[] = {")
    for chal in challenges:
        chal_id = chal["id"]
        pts = chal.get("_calculated_total_points", 0)
        q_count = len(chal.get("questions", []))
        q_ptr = f"q_{chal_id}" if q_count > 0 else "0"

        c_source.append(f'    {{ .id_string = "{chal_id}", .total_points = {pts}, '
                        f'.question_count = {q_count}, .questions = {q_ptr} }},')

    c_source.append("};")
    c_source.append("")
    c_source.append(f"const uint32_t g_challengedb_size = {len(challenges)};")

    os.makedirs(os.path.dirname(OUT_C), exist_ok=True)
    with open(OUT_C, 'w') as f:
        f.write("\n".join(c_source))
    print(f"[*] Wrote Backend Database: {OUT_C}")

if __name__ == "__main__":
    main()
