/* AUTOGENERATED FILE - DO NOT EDIT */
#include <stdint.h>
#include "data/cg_challengedb_data.h"

static const struct cg_question q_fuzzer_001[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 1, .explanation = "Total Length is 0x0014 (20 bytes). Since the IP header is 20 bytes and the Protocol is TCP (0x06), there is no room left for the TCP header." },
};

static const struct cg_question q_fuzzer_002[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 3, .explanation = "The Flags field is 0x03, asserting both SYN and FIN simultaneously, which is an invalid state transition." },
};

static const struct cg_question q_fuzzer_003[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 2, .explanation = "A checksum of 0x0000 means it was uncalculated. While permitted in IPv4 UDP, it is strictly illegal in IPv6." },
};

static const struct cg_question q_fuzzer_004[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 1, .explanation = "The IHL (Internet Header Length) is the second nibble of the first byte[cite: 5, 6]. It is set to 0xF (15), which means the header should be 60 bytes (15 * 4). However, the Total Length field is 0x0040 (64 bytes), and the IP header options cannot exceed the boundary of the packet if additional protocol data is expected[cite: 10, 11]." },
};

static const struct cg_question q_fuzzer_005[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 2, .explanation = "The 'Flags / Fragment Offset' field is 0x2000. This sets the 'More Fragments' (MF) flag while keeping the Fragment Offset at 0. However, the Total Length is 0x001C (28 bytes). With a 20-byte IP header, the payload is only 8 bytes. Most transport protocols require a larger initial fragment, and a 'More Fragments' flag on a packet this small often indicates a Teardrop-style attack or a fuzzed offset inconsistency." },
};

static const struct cg_question q_instruction_001[] = {
    { .id = 1, .points = 50, .type = CG_ANS_TEXT, .answer.text_answer = "512", .explanation = "rbx is zeroed, 0x100 (256) is added, and it is logically shifted left by 1 (multiplied by 2), resulting in 512." },
};

static const struct cg_question q_instruction_002[] = {
    { .id = 1, .points = 50, .type = CG_ANS_TEXT, .answer.text_answer = "10", .explanation = "The stack is LIFO. rcx (10) was pushed last, so popping into rax places 10 into the register." },
};

static const struct cg_question q_instruction_003[] = {
    { .id = 1, .points = 50, .type = CG_ANS_TEXT, .answer.text_answer = "5", .explanation = "15 is less than 20. The LT (Less Than) conditional executes, placing 5 into r1." },
};

static const struct cg_question q_instruction_004[] = {
    { .id = 1, .points = 50, .type = CG_ANS_TEXT, .answer.text_answer = "240", .explanation = "rax (0xFF / 11111111) is ANDed with rdx (0x0F / 00001111), resulting in 0x0F (00001111). The NOT operation flips these bits to 11110000, which is 0xF0 or 240 in decimal." },
};

static const struct cg_question q_instruction_005[] = {
    { .id = 1, .points = 50, .type = CG_ANS_TEXT, .answer.text_answer = "37", .explanation = "The LEA (Load Effective Address) instruction performs the calculation: rax + (rcx * 4) + 7. Substituting the values: 10 + (5 * 4) + 7 = 10 + 20 + 7 = 37." },
};

static const struct cg_question q_protocol_001[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 3, .explanation = "The Opcode field (0x0001) dictates this is a request." },
};

static const struct cg_question q_protocol_002[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 2, .explanation = "A Type 8, Code 0 structure represents an Echo Request." },
};

static const struct cg_question q_protocol_003[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 3, .explanation = "The Handshake Type (0x01) specifically identifies this payload as a Client Hello." },
};

static const struct cg_question q_protocol_004[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 2, .explanation = "The Client IP Address (offsets 12-15) is 0x00000000. This indicates the client does not yet have an assigned IP and is likely in the Discover or Request phase[cite: 5, 6, 7]." },
};

static const struct cg_question q_protocol_005[] = {
    { .id = 1, .points = 50, .type = CG_ANS_SINGLE, .answer.numeric_answer = 1, .explanation = "The Flags field (0x0100) has the 'QR' bit (bit 15) set to 0, indicating a Query. The 'RD' bit (bit 8) is set to 1, indicating that Recursion is Desired." },
};

const struct cg_challengedb g_challengedb[] = {
    { .id_string = "fuzzer_001", .total_points = 50, .question_count = 1, .questions = q_fuzzer_001 },
    { .id_string = "fuzzer_002", .total_points = 50, .question_count = 1, .questions = q_fuzzer_002 },
    { .id_string = "fuzzer_003", .total_points = 50, .question_count = 1, .questions = q_fuzzer_003 },
    { .id_string = "fuzzer_004", .total_points = 50, .question_count = 1, .questions = q_fuzzer_004 },
    { .id_string = "fuzzer_005", .total_points = 50, .question_count = 1, .questions = q_fuzzer_005 },
    { .id_string = "instruction_001", .total_points = 50, .question_count = 1, .questions = q_instruction_001 },
    { .id_string = "instruction_002", .total_points = 50, .question_count = 1, .questions = q_instruction_002 },
    { .id_string = "instruction_003", .total_points = 50, .question_count = 1, .questions = q_instruction_003 },
    { .id_string = "instruction_004", .total_points = 50, .question_count = 1, .questions = q_instruction_004 },
    { .id_string = "instruction_005", .total_points = 50, .question_count = 1, .questions = q_instruction_005 },
    { .id_string = "protocol_001", .total_points = 50, .question_count = 1, .questions = q_protocol_001 },
    { .id_string = "protocol_002", .total_points = 50, .question_count = 1, .questions = q_protocol_002 },
    { .id_string = "protocol_003", .total_points = 50, .question_count = 1, .questions = q_protocol_003 },
    { .id_string = "protocol_004", .total_points = 50, .question_count = 1, .questions = q_protocol_004 },
    { .id_string = "protocol_005", .total_points = 50, .question_count = 1, .questions = q_protocol_005 },
};

const uint32_t g_challengedb_size = 15;