/* AUTOGENERATED FILE - DO NOT EDIT */
#include <stdint.h>
#include "data/cg_challengedb_data.h"

static const struct cg_question q_instruction_001[] = {
    { .id = 1, .points = 25, .type = CG_ANS_TEXT, .answer.text_answer = "Hello, world!", .explanation = "The rax=1 syscall is 'sys_write', which prints our string to STDOUT." },
    { .id = 2, .points = 25, .type = CG_ANS_BITMASK, .answer.numeric_answer = 2, .explanation = "[Windows]: Incorrect. Windows uses the NT kernel API, not Linux syscall numbers.\\n[Linux]: Correct. Syscalls 1 (write) and 60 (exit) match the x86_64 Linux ABI." },
};

const struct cg_challengedb g_challengedb[] = {
    { .id_string = "instruction_001", .total_points = 50, .question_count = 2, .questions = q_instruction_001 },
};

const uint32_t g_challengedb_size = 1;
