
name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang gcc make mold nasm python3

    - name: Compile
      run: make debug

    - name: Run tests
      run: python3 tests/test_fcgi.py

    - name: Verify build artifacts
      run: |
        if [ ! -f bin/debug/compuguessr ]; then
          echo "Binary not found!"
          exit 1
        fi
        echo "Build and tests are successful."
