
name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make python3-pytest python3-requests

    - name: Compile with development image
      run: |
        make docker-build-native
        docker compose run --name cg_builder compuguessr-dev-native make debug

    - name: Extract and Prepare Binary
      run: |
        mkdir -p bin/debug build/debug
        docker cp cg_builder:/app/bin/debug/compuguessr ./bin/debug/compuguessr
        docker cp cg_builder:/app/build/debug ./build/
        docker rm cg_builder
        chmod +x bin/debug/compuguessr

    - name: Run tests
      run: pytest test

    - name: Verify build artifacts
      run: |
        if [ ! -f bin/debug/compuguessr ]; then
          echo "Binary not found!"
          exit 1
        fi
        echo "Build and tests are successful."
